repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
      exclude: cfn
    - id: check-json
    - id: trailing-whitespace
      args: ["--markdown-linebreak-ext=md"]
    - id: check-added-large-files
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: detect-private-key
    - id: detect-aws-credentials
      args: ["--allow-missing-credentials"]
    - id: end-of-file-fixer
    - id: name-tests-test
    - id: no-commit-to-branch
    - id: requirements-txt-fixer
    - id: pretty-format-json
      args:
        - --autofix
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.18.0
  hooks:
    - id: gitleaks
- repo: https://github.com/bridgecrewio/checkov.git
  rev: 2.4.22
  hooks:
    - id: checkov
      args:
        - --config-file
        - .checkov.yaml
- repo: https://github.com/terraform-docs/terraform-docs
  rev: "v0.16.0"
  hooks:
    - id: terraform-docs-go
      args: ["markdown", "table", "--output-file", "README.md", "./src/tf_dns"]
- repo: https://github.com/rhysd/actionlint
  rev: v1.6.25
  hooks:
    - id: actionlint
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
      exclude: 'src/tf_ec2/ami_discovery/[^/]+$'
      args:
      - --hook-config=--retry-once-with-cleanup=true
    - id: terraform_tflint
      args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      args:
        - --ignore=B907,E203,W503
      additional_dependencies:
        - flake8-bugbear
        - flake8-comprehensions
        - flake8-simplify
- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: env HOSTED_ZONE_ID=local HOSTED_ZONE_DOMAIN=test DYNAMODB_TABLE=test pytest
      args:
        - ./tests/unit_tests
      language: system
      types: [python]
      pass_filenames: false
      always_run: true
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
    - id: bandit
      args:
        - -x
        - tests,src/snow/snow/settings.py
