[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox
)/
'''

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src/lambda"
testpaths = ["tests"]
log_cli = true
log_cli_level = "CRITICAL"
log_cli_format = "%(message)s"
