# Generated by Django 4.2.5 on 2023-09-10 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(default="/dev/xvda", max_length=30)),
                ("volume_size", models.IntegerField(default=8)),
                ("volume_type", models.CharField(default="gp3", max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="EC2Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("ami_filter", models.CharField(default="N/A", max_length=30)),
                (
                    "ami_id",
                    models.CharField(default="ami-00a9282ce3b5ddfb1", max_length=30),
                ),
                ("discovered", models.BooleanField(default=False)),
                ("imported", models.BooleanField(default=False)),
                ("instance_id", models.CharField(default="", max_length=30)),
                ("operational", models.BooleanField(default=False)),
                ("region", models.CharField(default="us-east-2", max_length=30)),
                ("subnet_id", models.CharField(default="", max_length=30)),
                ("type", models.CharField(default="t2.micro", max_length=15)),
                ("ebs_block_devices", models.ManyToManyField(to="ec2.blockdevice")),
                (
                    "root_block_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ec2_servers",
                        to="ec2.blockdevice",
                    ),
                ),
            ],
        ),
    ]
