# Generated by Django 4.2.5 on 2023-09-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ec2", "0002_alter_ec2server_operational"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ec2server",
            name="ebs_block_devices",
            field=models.ManyToManyField(blank=True, to="ec2.blockdevice"),
        ),
    ]
