# Generated by Django 4.2.5 on 2023-09-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ec2", "0003_alter_ec2server_ebs_block_devices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ec2server",
            name="instance_id",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="ec2server",
            name="subnet_id",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
