# Generated by Django 4.2.5 on 2023-09-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ec2", "0004_alter_ec2server_instance_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ec2server",
            options={
                "verbose_name": "EC2 Server",
                "verbose_name_plural": "EC2 Servers",
            },
        ),
        migrations.AlterField(
            model_name="ec2server",
            name="ami_id",
            field=models.CharField(
                blank=True, default="ami-00a9282ce3b5ddfb1", max_length=30
            ),
        ),
    ]
