# Generated by Django 4.2.5 on 2023-09-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ec2", "0005_alter_ec2server_options_alter_ec2server_ami_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockdevice",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="blockdevice",
            name="volume_id",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
