# Generated by Django 4.2.5 on 2023-09-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ec2", "0005_alter_ec2server_options_alter_ec2server_ami_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(default="Name", max_length=30)),
                ("value", models.CharField(default="Server1", max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name="ec2server",
            name="tags",
            field=models.ManyToManyField(blank=True, to="ec2.tag"),
        ),
    ]
