# Generated by Django 4.2.5 on 2023-09-24 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ec2", "0006_tag_ec2server_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("interval", models.IntegerField(default=30)),
                ("path", models.CharField(default="/", max_length=30)),
                ("port", models.CharField(default="traffic-port", max_length=30)),
                ("healthy_threshold", models.IntegerField(default=3)),
                ("unhealthy_threshold", models.IntegerField(default=3)),
                ("timeout", models.IntegerField(default=6)),
                ("protocol", models.CharField(default="HTTP", max_length=30)),
                ("matcher", models.CharField(default="200-399", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Listener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port", models.IntegerField()),
                ("protocol", models.CharField(max_length=30)),
                ("target_group_index", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="SecurityGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sg_id", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Subnet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subnet_id", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="TargetGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_prefix", models.CharField(max_length=30)),
                ("backend_protocol", models.CharField(max_length=30)),
                ("backend_port", models.IntegerField(default=80)),
                ("target_type", models.CharField(default="instance", max_length=30)),
                (
                    "health_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_groups",
                        to="ec2.healthcheck",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ALB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("vpc_id", models.CharField(max_length=30)),
                ("internal", models.BooleanField(default=False)),
                ("discovery_tag", models.CharField(max_length=30)),
                (
                    "http_tcp_listeners",
                    models.ManyToManyField(blank=True, to="ec2.listener"),
                ),
                (
                    "security_groups",
                    models.ManyToManyField(blank=True, to="ec2.securitygroup"),
                ),
                ("subnets", models.ManyToManyField(blank=True, to="ec2.subnet")),
                (
                    "target_groups",
                    models.ManyToManyField(blank=True, to="ec2.targetgroup"),
                ),
            ],
            options={
                "verbose_name": "Application LB",
                "verbose_name_plural": "Application LBs",
            },
        ),
    ]
