# Generated by Django 4.2.5 on 2023-09-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ec2", "0007_healthcheck_listener_securitygroup_subnet_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alb",
            name="subnets",
        ),
        migrations.AddField(
            model_name="alb",
            name="operational",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name="Subnet",
        ),
    ]
