name: "Create PR loadbalancers"
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  create_pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Make changes to pull request
        run: |
          pip install boto3 python-hcl2
          cp -pa src/data/albs.tfvars src/data/albs.tfvars.temp
          python src/dynamo/discover_lb_targets.py
          rm -f src/data/albs.tfvars.temp

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform fmt
        id: fmt
        run: terraform fmt src/data/
        continue-on-error: true

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: Add job
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: add/alb
          delete-branch: true
          title: '[ADD] Add ALB'
          body: |
            Add ALBs
            - new alb(s) on AWS.
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            alb
            automated pr
            update
          draft: false
