name: "Create PR discovered"
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  create_pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Discover EC2s script
        run: |
          pip install boto3
          python src/dynamo/discover_ec2.py

      - name: Make changes to pull request
        run: |
          pip install boto3 python-hcl2
          cp -pa src/data/ec2.tfvars src/data/ec2.tfvars.temp
          python src/dynamo/import_ec2.py
          rm -f src/data/ec2.tfvars.temp

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform fmt
        id: fmt
        run: |
          terraform fmt src/data/
          terraform fmt src/terraform2/
        continue-on-error: true

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: import job
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: import/ec2
          delete-branch: true
          title: '[Import] Update EC2'
          body: |
            Import EC2 instances
            - new imported instance(s).
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            ec2
            automated pr
            import
          draft: false
